### ISSUE TITLE
Sync issue from PMP to PRP

### ISSUE THREAD

**Issue by robertavram** [unicef/etools-partner-reporting-portal#935]
when synching PDs in Iraq I'm getting:
```
[2018-10-01 19:09:20,951: WARNING/Worker-1] Processing PD: 452
[2018-10-01 19:09:21,142: WARNING/Worker-1] {'non_field_errors': ['The fields title, p_code must make a unique set.']}
[2018-10-01 19:09:21,148: ERROR/MainProcess] Task unicef.tasks.process_programme_documents[3fc98500-4973-49d0-92a8-48b86ba9350e] raised unexpected: ValidationError({'non_field_errors': ['The fields title, p_code must make a unique set.']},)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/django_api/apps/unicef/tasks.py", line 419, in process_programme_documents
    'p_code': l['pcode'],
  File "/code/django_api/apps/unicef/tasks.py", line 56, in process_model
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 245, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'non_field_errors': ['The fields title, p_code must make a unique set.']}
```
when I checked the set of locations in PMP, it seems like there is no two locations with the same name or pcode.. On the PD there are two indicators with the same location set

**Comment by robertavram** [comment]
currently this can be seen in the logs on the worker containers in Rancher PRP-dev

**Comment by n1207n** [comment]
@robertavram, I notice that some of the PMP locations (including the ones crashing) have admin level of 3-5, which we don't have from CartoDB platform. Hence, the celery task tries to create these new locations during PD sync. However, the logic is wrapped with transaction.atomic block, so when the first instance of new location is found, it's technically committed to the transaction.

When the next instance comes in, it's violating the withstanding transaction I think.

This is kinda chicken-and-egg situation. We want title and pcode to be unique_together as that is fair validation to have in our Location model. To solve this, we may ask PMP team to upload missing Iraq locations to CartoDB. Once we sync these from CartoDB, PD sync won't treat locations to create.

**Comment by robertavram** [comment]
updating all locations in Iraq on our side could be problematic. Let me look into it and get back asap

**Comment by n1207n** [comment]
@robertavram any update on this?

**Comment by robertavram** [comment]
I've manually changed all problematic locations in Iraq.. testing can go ahead in Iraq..
We're now working on the migration script for all other countries..

**Comment by n1207n** [comment]
Closing this as PD sync seems normal now.
