### ISSUE TITLE
Report sync is not working

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#952]
dev.prp environment
Iraq workspace

report generator is not working, error message:

[2018-10-05 13:36:37,709: WARNING/Worker-1] Creating Quantity IndicatorReport for 2018-09-12 - 2018-09-18
[2018-10-05 13:36:37,721: WARNING/Worker-1] Creating IndicatorReport Dual Testing Indicator For Oct4 IndicatorLocationData for 2018-09-12 - 2018-09-18
[2018-10-05 13:36:37,736: WARNING/Worker-1] Creating IndicatorReport Dual Testing Indicator For Oct4 IndicatorLocationData for 2018-09-12 - 2018-09-18
[2018-10-05 13:36:37,747: WARNING/Worker-1] Creating IndicatorReport Dual Testing Indicator For Oct4 IndicatorLocationData for 2018-09-12 - 2018-09-18
[2018-10-05 13:36:37,778: ERROR/MainProcess] Task core.tasks.process_period_reports[f4a1ec39-88df-4ab2-a94c-6ab7b5f5f36b] raised unexpected: MultipleObjectsReturned('get() returned more than one Reportable -- it returned 42!',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/django_api/apps/core/tasks.py", line 526, in process_period_reports
    due_date
  File "/code/django_api/apps/core/tasks.py", line 417, in create_ir_and_ilds_for_pr
    pai_indicator = cai_indicator.children.get(partner_activities__partner=pd.partner)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 384, in get
    (self.model._meta.object_name, num)
indicator.models.MultipleObjectsReturned: get() returned more than one Reportable -- it returned 42!

**Comment by KKaselkar** [comment]
https://dev.partnerreportingportal.org/app/IRQ/ip-reporting/pd/960/report/1392/edit?page=1

reports are generated.
